GET http://localhost:5050/users

######

POST http://localhost:5050/users HTTP/1.1
content-type: application/json

{
    "userName": "gianluca",
    "email": "gianlucacobucci330@gmail.com",
    "password": "hello"
}

######

POST http://localhost:5050/login HTTP/1.1
content-type: application/json

{
    "email": "gianlucacobucci330@gmail.com",
    "password": "hello"
}